from pathlib import Path

# Experiment configuration
SEED = 42
HORIZON = 1_000
BANDIT_REPLICATES = 20
ADVERSARIAL_ACTIONS = 3
ADVERSARIAL_MEMORY_WINDOW = 0

# Numerical configuration
NUMERICAL_TOLERANCE = 1e-10
STATIONARY_METHOD = "solve"
EQUILIBRIUM_LP_TOLERANCE = 1e-8

# Output directories
RESULTS_DIR = Path("results")
RAW_DIR = RESULTS_DIR / "raw"
FIGURE_DIR = RESULTS_DIR / "figures"
ADVERSARIAL_DIR = RESULTS_DIR / "adversarial"
ADVERSARIAL_RAW_DIR = ADVERSARIAL_DIR / "raw"
ADVERSARIAL_FIGURE_DIR = ADVERSARIAL_DIR / "figures"
CUSTOM_GAME_DIR = Path("data") / "custom_games"
