from pathlib import Path

# Experiment configuration
SEED = 42
HORIZON = 1_000
REPLICATES = 20
ADVERSARIAL_ACTIONS = 3
ACTION_SCALING_ACTION_COUNTS = (2, 3, 5, 10)

# Numerical configuration
NUMERICAL_TOLERANCE = 1e-10
STATIONARY_METHOD = "solve"
EQUILIBRIUM_LP_TOLERANCE = 1e-8

# Output directories
RESULTS_DIR = Path("results")
RAW_DIR = RESULTS_DIR / "raw"
FIGURE_DIR = RESULTS_DIR / "figures"
ADVERSARIAL_DIR = RESULTS_DIR / "adversarial"
ADVERSARIAL_RAW_DIR = ADVERSARIAL_DIR / "raw"
ADVERSARIAL_FIGURE_DIR = ADVERSARIAL_DIR / "figures"
ADVERSARIAL_SCALING_DIR = ADVERSARIAL_DIR / "scaling"
ADVERSARIAL_SCALING_RAW_DIR = ADVERSARIAL_SCALING_DIR / "raw"
ADVERSARIAL_SCALING_FIGURE_DIR = ADVERSARIAL_SCALING_DIR / "figures"
CUSTOM_GAME_DIR = Path("data") / "custom_games"
