import numpy as np

from obsolete.single_player.base import SinglePlayerEnvironment


class StochasticBandit(SinglePlayerEnvironment):
    """
    Stochastic bandit problem with independent arm distributions.

    Each arm has a fixed mean reward.

    Rewards are generated by a sampling function.
    """

    def __init__(self, means: list[float], sampler):
        if len(means) == 0:
            raise ValueError("means must not be empty")

        self._means = np.asarray(means, dtype=float)
        self._sampler = sampler
        self._optimal_action = int(np.argmax(self._means))

    @property
    def n_actions(self) -> int:
        return len(self._means)

    @property
    def optimal_action(self) -> int:
        return self._optimal_action

    def step(self, action: int) -> float:
        self._validate_action(action)
        return float(self._sampler(action))

    def pull(self, arm: int) -> float:
        """
        Alias for step() using standard bandit terminology.
        """
        return self.step(arm)

    def arm_mean(self, arm: int) -> float:
        self._validate_action(arm)
        return float(self._means[arm])

    def optimal_mean(self) -> float:
        return float(self._means[self._optimal_action])

    def __repr__(self) -> str:
        return f"StochasticBandit(means={self._means.tolist()})"


class BernoulliBandit(StochasticBandit):
    """
    Bernoulli bandit problem.

    Each action a has reward distribution

        X ~ Bernoulli(p_a)
    """

    def __init__(self, probs):
        if len(probs) == 0:
            raise ValueError("probs must not be empty")
        for p in probs:
            if p < 0.0 or p > 1.0:
                raise ValueError("probs must be in [0, 1]")

        super().__init__(
            means=probs,
            sampler=lambda a: np.random.binomial(1, probs[a]),
        )

    def __repr__(self) -> str:
        return f"BernoulliBandit(probs={self._means.tolist()})"


class GaussianBandit(StochasticBandit):
    """
    Gaussian bandit problem.

    Each action a has reward distribution

        X ~ N(mu_a, sigma^2)
    """

    def __init__(self, means, sigma=1.0):
        if len(means) == 0:
            raise ValueError("means must not be empty")
        if sigma <= 0.0:
            raise ValueError("sigma must be positive")

        self._sigma = float(sigma)
        super().__init__(
            means=means,
            sampler=lambda a: np.random.normal(means[a], self._sigma),
        )

    def __repr__(self) -> str:
        return f"GaussianBandit(means={self._means.tolist()}, sigma={self._sigma})"
